#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

##############################################################################

cd cluster-autoscaler
go test $(go list ./... | grep -v cloudprovider | grep -v integration)
go test $(go list ./cloudprovider/mcm/...)

#TODO: Return success failure properly
echo "CI tests are done"
