#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

##############################################################################
if [ "$GITHUB_ACTIONS" = "true" ]; then
    # echo "=== disk-usage for /usr Level 2 ==="
    # sudo du -xh --exclude=/proc --max-depth=2 / | sort -hr

    echo "=== Deleting un-needed framework/tool dirs ==="

    sudo rm -rf /usr/local/.ghcup || true # haskell installer: ~6.4GB
    sudo rm -rf /usr/share/dotnet || true # dotnet: ~4GB
    sudo rm -rf /usr/share/swift  || true # swift: ~3.2GB
    sudo rm -rf /usr/lib/jvm || true      # jvm: ~1.5GB

    # echo "=== Github Workspace Usage for $GITHUB_WORKSPACE ==="
    # du -h --max-depth=1 "$GITHUB_WORKSPACE" | sort -hr
fi

echo "=== Running cluster-autoscaler unit-tests..."

cd cluster-autoscaler
go test $(go list ./... | grep -v cloudprovider | grep -v integration)
go test $(go list ./cloudprovider/mcm/...)

#TODO: Return success failure properly
echo "CI tests are done"
